### ISSUE TITLE
overrideBrowserslist without global browserslist in the package.json

### ISSUE THREAD

**Issue by Zobakka** [FARCER/Start-template-gulp-4-pug-sass#10]
В одной из недавних правок в опциях autoprefixer была заменена опция browsers: ['last 3 version'] на overrideBrowserslist:  ['last 3 versions'], поскольку первая устарела в новой версии автопрефиксера.

Насколько разумно использовать overrideBrowserslist в самом автопрефиксере, если в package.json отсутствует то, что надо перезаписывать?

Не правильнее ли будет добавить в package.json опцию наподобие:

"browserslist": [
    "last 2 version",
    "> 1%",
    "maintained node versions",
    "not dead"
  ]

и использовать единую конфигурацию для всех плагинов, чтобы не приводить к возможным конфликтам?

А если так надо, то например, при определенной сборке использовать overrideBrowserslist автопрефиксера...

**Comment by FARCER** [comment]
Согласен с вами. Будет исправлено в ближайшее время

**Comment by Zobakka** [comment]
Добрый день Анатолий! Я поправил у себя и могу сделать pull request, если хотите. Если вы не против, то скажите в какую ветку?

**Comment by FARCER** [comment]
Кидайте в мастер

**Comment by FARCER** [comment]
Принял пул реквест
