### ISSUE TITLE
Компиляция pug

### ISSUE THREAD

**Issue by vitalbielik** [FARCER/Start-template-gulp-4-pug-sass#18]
Нашел решение проблемы долгой компиляции pug
До этого у меня pug (лично на моем проекте) компилился где то 5-8 секунд. После некоторых доработок компиляция стала примерно 400-700ms

Что нужно сделать:
в файле pug.js в строку "return $.gulp.src('./dev/pug/*.pug'" - дописать параметр 
" {since: $.gulp.lastRun('dev')}"

![image](https://user-images.githubusercontent.com/37478975/73167216-22ed3d80-4100-11ea-8d6c-bc73729a89a3.png)

P.S "dev" - это наша папка с робочими файлами. важно написать именно ее а не "./dev/pug"

**Comment by FARCER** [comment]
Данное решение отслеживает только папку dev и не следит за другими файлами
