### ISSUE TITLE
Проблема с импортом стилей из node_nodules

### ISSUE THREAD

**Issue by FoxMalder** [FARCER/Start-template-gulp-4-pug-sass#2]
Скачал slick-carousel: yarn add slick-carousel. В файле libs.scss делаю так:  "@import "../../../../node_modules/slick-carousel/slick/slick.css" "; и получаю в консоли браузера:

"Refused to apply style from 'http://localhost:3000/node_modules/slick-carousel/slick/slick.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

У вас такое было? Как ее решить?

Я так понял, что проблема с импортом возникает именно у css файлов, т.к. если импортировать scss, то все хорошо. Вопрос остается открытым: как импортировать css файл?

**Comment by demas585** [comment]
Проблема не проекта. Не нужно указывать расширение при импорте css файла.
