### ISSUE TITLE
Task never defined: html:dev

### ISSUE THREAD

**Issue by BlackFxTalon** [FARCER/Start-template-gulp-4-pug-sass#3]
Привет, решил использовать твой классный шаблон, но столкнулся с ошибкой при выполнении таска -  выдает ошибку rtionError [ERR_ASSERTION]: Task never defined: html:dev. Пример моего галпфайла - https://codepen.io/anon/pen/mQYjEv

**Comment by FARCER** [comment]
Привет. Ошибка говорит о том, что таска такого нет. Создайте его и все.
