### ISSUE TITLE
Откуда берётся JQuery в папке build 

### ISSUE THREAD

**Issue by smargelov** [FARCER/Start-template-gulp-4-pug-sass#5]
Не могу понять, откуда берётся JQuery 3.3.1 каждый раз при создании папки build? В каком таске это прописано? Хочу удалить, так как привык все сторонние библиотеки одним файлом вставлять. 
Заранее благодарен

**Comment by FARCER** [comment]
Удалите отсюда файл и все https://github.com/FARCER/Start-template-gulp-4-pug-sass/tree/master/dev/static/js

**Comment by smargelov** [comment]
Спасибо. Был невнимателен. Ещё раз — огромное спасибо стартовый шаблон.
