### ISSUE TITLE
gulp-changed (Destination directory)

### ISSUE THREAD

**Issue by motrdevua** [FARCER/Start-template-gulp-4-pug-sass#9]
в файле gulp/tasks/pug.js в строке:
`.pipe(changed('dist', {extension: '.html'}))`

Не верно указано имя папки для слежки.
В доках gulp-changed написано (Destination directory. Same as you put into gulp.dest().)
В вашем шаблоне папка названа build.
Следовательно идёт обработка всех файлов, включая не изменённые.

**Comment by FARCER** [comment]
Готово

**Comment by kirill-2l** [comment]
После изменения .pipe(changed('dist', {extension: '.html'})) на 
.pipe(changed('build', {extension: '.html'}))
переставало вотчить папку modules

**Comment by FARCER** [comment]
Исправил
